// flow-typed signature: 8fc4e3474a3765a2afb6a548d32dc1b4
// flow-typed version: <<STUB>>/p-reduce_v^1.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-reduce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-reduce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'p-reduce/index' {
  declare module.exports: $Exports<'p-reduce'>;
}
declare module 'p-reduce/index.js' {
  declare module.exports: $Exports<'p-reduce'>;
}
